language: node_js
node_js:
- '8'
cache: yarn
sudo: false
script:
- yarn lint
- yarn deploy
env:
  secure: mPbAp8SBmhtnf7XULprkTW2XKf1voffhadOAtXsEThWv28RUD/qwNFwOhJhX5dqDloCCN7IFmFBpm35dxyS6dHXpYivVidGhK3kuQ9HAdJdUvCAz7cmehpI8jZBfaeBjGWbiyXbPmK/j0TFHVlTtpc8nQlUTaSZqlXSYWAXqvXUGYjINd+q1AQ4TSG8WSsLW/OAXVyMqo9l+PJeVpuAJ/pcPwLK5GDzfEavJt/M0YaJGwbPtZGu9MZgQsdz8X1WT2XAcWA/TU4wEsl3uXThwi/HTFcoz+mZn+NOLGQLiBbZOrdC5fOtfwTN6t75vl8btaAMdr3utYj/ahHCnenrmy0Ie214NHy5N3DMX76etr6cG10NdxnQjlyZwlITI/3Y51PkV9fd+AZB4Nn+3g4LDgG3PzS/+Vzk4/vC8sX9SanvRme0iISVQO6nm7wpZ6vhattJbwB0QAYi7oDyHN4p1ZKAR6ac7cphEm4ZZ4+jqMPByCJggKeW7uWexceYCE2dtisa/pGexT6wEmxGDcuUE38xomkx+NynzdgvMVIYK0yGIHy4e9KJP+HrJ3dyEf2/DPzhg1eMZY3sbF3uJXhIEU5e0ZSkaSSRoSES/MaGTuO+GTRlpotiMPYAZbwuBl2bKELnuBg1fNd4d0BGjiHnXjCkVG3MgeGmshDISe+GTT1A=
