language: node_js
node_js:
- '8'
cache: yarn
sudo: false
script:
- yarn lint
- yarn deploy
env:
  global:
    secure: HUgkD9MASuCX+Ip+POZ+NZlyyd8Xr/mCAZBSJ/EGkVEsCHCsgdzYbM7wYne11XhS43r+BYAc+pUQipXBdpaByRbV1AvBtRm4NPNgPvDtj0hwUGuenRxMDSQb1kDOdluPOmbrDTC4ZwiJS9Nz9Nlycq4KxdZtKJPCjC7yk1xq5gZ9Gam85iF1BnhhdM3c8c5ZjjBzSbi/6rA3kCAmSPHlrlrRZMNO+8mUzBkzWhGF6AnCWCGCBbGLYVMgD4waw/+eIzaFYa6RPcQCE3oC7hwRE7VHcL+AI9fhvqTYGEhyMmpzsZMosY2eO0y0q5X7HLLIk37evfoMwXDT5exCffyDJqV0BTHbAUwR11oSkYzcdJUPNqvoEaEV0cm3quivB0r/Xy5r94pBtWe3skLxGj1lhydEMq6RglPJ+LGkZYFJB7OpHJ3mSu9kAJBvPZMr+ymGnCKJx8z0nSREOXLtA10cIodl6RH4iz4FmMBltsg98fVyXsXHMF7aiwtjkORXLawtt+OuBGNcgk2zyICPX49xnUFVbNCXhVyDgGXk2Kb3MxAvWbRoYsvlMH8hBMixSg4KbGWrvXMBmORCiDWpTgSw7uhwfA1DF+WqhzoEe6b+0ZLThygS/b8zQBSoMVDAnvJIlAmjinE9neUNu3hQEicsD4zgPnHsonKrqSZsp9MrCTo=
